// Netpaytool City Data — netpaytool.com
// Cost-of-living index, median salary, and state mapping per metro.
// COL index: 100 = national average. Source: C2ER 2024 / BLS OES 2024.

export interface CityData {
  name: string;
  state: string;
  stateCode: string;
  colIndex: number;         // cost-of-living index (100 = US average)
  medianSalary: number;     // BLS 2024 OES metro median annual wage
  localIncomeTax?: number;  // local income tax rate if applicable (e.g. NYC = 0.03648)
  localTaxName?: string;    // label for local tax (e.g. "NYC local income tax")
}

export const CITY_DATA: Record<string, CityData> = {
  "houston-tx": {
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    colIndex: 96,
    medianSalary: 45000,
  },
  "san-antonio-tx": {
    name: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    colIndex: 90,
    medianSalary: 42000,
  },
  "dallas-tx": {
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    colIndex: 100,
    medianSalary: 49000,
  },
  "austin-tx": {
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    colIndex: 115,
    medianSalary: 59000,
  },
  "fort-worth-tx": {
    name: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    colIndex: 93,
    medianSalary: 46000,
  },
  "phoenix-az": {
    name: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    colIndex: 105,
    medianSalary: 48000,
  },
  "tucson-az": {
    name: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    colIndex: 93,
    medianSalary: 37000,
  },
  "los-angeles-ca": {
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    colIndex: 164,
    medianSalary: 55000,
  },
  "san-diego-ca": {
    name: "San Diego",
    state: "California",
    stateCode: "CA",
    colIndex: 153,
    medianSalary: 63000,
  },
  "san-francisco-ca": {
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    colIndex: 194,
    medianSalary: 94000,
  },
  "sacramento-ca": {
    name: "Sacramento",
    state: "California",
    stateCode: "CA",
    colIndex: 116,
    medianSalary: 53000,
  },
  "denver-co": {
    name: "Denver",
    state: "Colorado",
    stateCode: "CO",
    colIndex: 108,
    medianSalary: 56000,
  },
  "chicago-il": {
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    colIndex: 107,
    medianSalary: 47000,
  },
  "atlanta-ga": {
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    colIndex: 107,
    medianSalary: 52000,
  },
  "miami-fl": {
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    colIndex: 122,
    medianSalary: 42000,
  },
  "tampa-fl": {
    name: "Tampa",
    state: "Florida",
    stateCode: "FL",
    colIndex: 103,
    medianSalary: 45000,
  },
  "orlando-fl": {
    name: "Orlando",
    state: "Florida",
    stateCode: "FL",
    colIndex: 101,
    medianSalary: 44000,
  },
  "jacksonville-fl": {
    name: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    colIndex: 93,
    medianSalary: 43000,
  },
  "charlotte-nc": {
    name: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    colIndex: 101,
    medianSalary: 52000,
  },
  "raleigh-nc": {
    name: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    colIndex: 105,
    medianSalary: 56000,
  },
  "nashville-tn": {
    name: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    colIndex: 105,
    medianSalary: 52000,
  },
  "memphis-tn": {
    name: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    colIndex: 83,
    medianSalary: 35000,
  },
  "las-vegas-nv": {
    name: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    colIndex: 107,
    medianSalary: 45000,
  },
  "seattle-wa": {
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    colIndex: 152,
    medianSalary: 79000,
  },
  "portland-or": {
    name: "Portland",
    state: "Oregon",
    stateCode: "OR",
    colIndex: 119,
    medianSalary: 55000,
  },
  "minneapolis-mn": {
    name: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    colIndex: 105,
    medianSalary: 56000,
  },
  "columbus-oh": {
    name: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    colIndex: 91,
    medianSalary: 45000,
    localIncomeTax: 0.025,
    localTaxName: "Columbus municipal income tax",
  },
  "indianapolis-in": {
    name: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    colIndex: 88,
    medianSalary: 42000,
  },
  "detroit-mi": {
    name: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    colIndex: 83,
    medianSalary: 27000,
    localIncomeTax: 0.024,
    localTaxName: "Detroit city income tax",
  },
  "philadelphia-pa": {
    name: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    colIndex: 104,
    medianSalary: 40000,
    localIncomeTax: 0.038398,
    localTaxName: "Philadelphia wage tax (residents)",
  },
  "new-york-city-ny": {
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    colIndex: 187,
    medianSalary: 50000,
  },
  "boston-ma": {
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    colIndex: 162,
    medianSalary: 71000,
  },
  "baltimore-md": {
    name: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    colIndex: 108,
    medianSalary: 42000,
    localIncomeTax: 0.032,
    localTaxName: "Baltimore City local income tax",
  },
  "louisville-ky": {
    name: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    colIndex: 88,
    medianSalary: 42000,
    localIncomeTax: 0.0228,
    localTaxName: "Jefferson County occupational tax",
  },
  "kansas-city-mo": {
    name: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    colIndex: 90,
    medianSalary: 45000,
    localIncomeTax: 0.01,
    localTaxName: "Kansas City earnings tax",
  },
  "salt-lake-city-ut": {
    name: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    colIndex: 109,
    medianSalary: 58000,
  },
  "richmond-va": {
    name: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    colIndex: 101,
    medianSalary: 48000,
  },
  "albuquerque-nm": {
    name: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    colIndex: 90,
    medianSalary: 41000,
  },
  "oklahoma-city-ok": {
    name: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    colIndex: 87,
    medianSalary: 42000,
  },
  "milwaukee-wi": {
    name: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    colIndex: 93,
    medianSalary: 37000,
  },
  "montgomery-al": {
    name: "Montgomery",
    state: "Alabama",
    stateCode: "AL",
    colIndex: 79,
    medianSalary: 35000,
  },
  "huntsville-al": {
    name: "Huntsville",
    state: "Alabama",
    stateCode: "AL",
    colIndex: 88,
    medianSalary: 49000,
  },
  "mobile-al": {
    name: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    colIndex: 82,
    medianSalary: 33000,
  },
  "tuscaloosa-al": {
    name: "Tuscaloosa",
    state: "Alabama",
    stateCode: "AL",
    colIndex: 81,
    medianSalary: 36000,
  },
  "fairbanks-ak": {
    name: "Fairbanks",
    state: "Alaska",
    stateCode: "AK",
    colIndex: 118,
    medianSalary: 52000,
  },
  "juneau-ak": {
    name: "Juneau",
    state: "Alaska",
    stateCode: "AK",
    colIndex: 125,
    medianSalary: 62000,
  },
  "sitka-ak": {
    name: "Sitka",
    state: "Alaska",
    stateCode: "AK",
    colIndex: 122,
    medianSalary: 54000,
  },
  "ketchikan-ak": {
    name: "Ketchikan",
    state: "Alaska",
    stateCode: "AK",
    colIndex: 120,
    medianSalary: 50000,
  },
  "fort-smith-ar": {
    name: "Fort Smith",
    state: "Arkansas",
    stateCode: "AR",
    colIndex: 79,
    medianSalary: 35000,
  },
  "fayetteville-ar": {
    name: "Fayetteville",
    state: "Arkansas",
    stateCode: "AR",
    colIndex: 88,
    medianSalary: 45000,
  },
  "springdale-ar": {
    name: "Springdale",
    state: "Arkansas",
    stateCode: "AR",
    colIndex: 85,
    medianSalary: 42000,
  },
  "jonesboro-ar": {
    name: "Jonesboro",
    state: "Arkansas",
    stateCode: "AR",
    colIndex: 80,
    medianSalary: 37000,
  },
  "new-haven-ct": {
    name: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    colIndex: 120,
    medianSalary: 39000,
  },
  "hartford-ct": {
    name: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    colIndex: 115,
    medianSalary: 35000,
  },
  "stamford-ct": {
    name: "Stamford",
    state: "Connecticut",
    stateCode: "CT",
    colIndex: 148,
    medianSalary: 73000,
  },
  "waterbury-ct": {
    name: "Waterbury",
    state: "Connecticut",
    stateCode: "CT",
    colIndex: 112,
    medianSalary: 36000,
  },
  "dover-de": {
    name: "Dover",
    state: "Delaware",
    stateCode: "DE",
    colIndex: 98,
    medianSalary: 42000,
  },
  "newark-de": {
    name: "Newark",
    state: "Delaware",
    stateCode: "DE",
    colIndex: 105,
    medianSalary: 46000,
  },
  "middletown-de": {
    name: "Middletown",
    state: "Delaware",
    stateCode: "DE",
    colIndex: 107,
    medianSalary: 59000,
  },
  "smyrna-de": {
    name: "Smyrna",
    state: "Delaware",
    stateCode: "DE",
    colIndex: 100,
    medianSalary: 47000,
  },
  "hilo-hi": {
    name: "Hilo",
    state: "Hawaii",
    stateCode: "HI",
    colIndex: 150,
    medianSalary: 45000,
  },
  "kailua-hi": {
    name: "Kailua",
    state: "Hawaii",
    stateCode: "HI",
    colIndex: 195,
    medianSalary: 83000,
  },
  "pearl-city-hi": {
    name: "Pearl City",
    state: "Hawaii",
    stateCode: "HI",
    colIndex: 185,
    medianSalary: 66000,
  },
  "waipahu-hi": {
    name: "Waipahu",
    state: "Hawaii",
    stateCode: "HI",
    colIndex: 180,
    medianSalary: 61000,
  },
  "meridian-id": {
    name: "Meridian",
    state: "Idaho",
    stateCode: "ID",
    colIndex: 106,
    medianSalary: 59000,
  },
  "nampa-id": {
    name: "Nampa",
    state: "Idaho",
    stateCode: "ID",
    colIndex: 96,
    medianSalary: 45000,
  },
  "idaho-falls-id": {
    name: "Idaho Falls",
    state: "Idaho",
    stateCode: "ID",
    colIndex: 90,
    medianSalary: 43000,
  },
  "pocatello-id": {
    name: "Pocatello",
    state: "Idaho",
    stateCode: "ID",
    colIndex: 86,
    medianSalary: 37000,
  },
  "cedar-rapids-ia": {
    name: "Cedar Rapids",
    state: "Iowa",
    stateCode: "IA",
    colIndex: 84,
    medianSalary: 43000,
  },
  "davenport-ia": {
    name: "Davenport",
    state: "Iowa",
    stateCode: "IA",
    colIndex: 82,
    medianSalary: 40000,
  },
  "sioux-city-ia": {
    name: "Sioux City",
    state: "Iowa",
    stateCode: "IA",
    colIndex: 82,
    medianSalary: 40000,
  },
  "iowa-city-ia": {
    name: "Iowa City",
    state: "Iowa",
    stateCode: "IA",
    colIndex: 90,
    medianSalary: 49000,
  },
  "overland-park-ks": {
    name: "Overland Park",
    state: "Kansas",
    stateCode: "KS",
    colIndex: 98,
    medianSalary: 65000,
  },
  "topeka-ks": {
    name: "Topeka",
    state: "Kansas",
    stateCode: "KS",
    colIndex: 82,
    medianSalary: 37000,
  },
  "olathe-ks": {
    name: "Olathe",
    state: "Kansas",
    stateCode: "KS",
    colIndex: 96,
    medianSalary: 63000,
  },
  "lawrence-ks": {
    name: "Lawrence",
    state: "Kansas",
    stateCode: "KS",
    colIndex: 88,
    medianSalary: 42000,
  },
  "baton-rouge-la": {
    name: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    colIndex: 92,
    medianSalary: 40000,
  },
  "shreveport-la": {
    name: "Shreveport",
    state: "Louisiana",
    stateCode: "LA",
    colIndex: 84,
    medianSalary: 35000,
  },
  "lafayette-la": {
    name: "Lafayette",
    state: "Louisiana",
    stateCode: "LA",
    colIndex: 88,
    medianSalary: 40000,
  },
  "lake-charles-la": {
    name: "Lake Charles",
    state: "Louisiana",
    stateCode: "LA",
    colIndex: 85,
    medianSalary: 37000,
  },
  "lewiston-me": {
    name: "Lewiston",
    state: "Maine",
    stateCode: "ME",
    colIndex: 93,
    medianSalary: 35000,
  },
  "bangor-me": {
    name: "Bangor",
    state: "Maine",
    stateCode: "ME",
    colIndex: 96,
    medianSalary: 37000,
  },
  "south-portland-me": {
    name: "South Portland",
    state: "Maine",
    stateCode: "ME",
    colIndex: 112,
    medianSalary: 50000,
  },
  "auburn-me": {
    name: "Auburn",
    state: "Maine",
    stateCode: "ME",
    colIndex: 91,
    medianSalary: 36000,
  },
  "gulfport-ms": {
    name: "Gulfport",
    state: "Mississippi",
    stateCode: "MS",
    colIndex: 84,
    medianSalary: 36000,
  },
  "southaven-ms": {
    name: "Southaven",
    state: "Mississippi",
    stateCode: "MS",
    colIndex: 88,
    medianSalary: 49000,
  },
  "hattiesburg-ms": {
    name: "Hattiesburg",
    state: "Mississippi",
    stateCode: "MS",
    colIndex: 79,
    medianSalary: 33000,
  },
  "biloxi-ms": {
    name: "Biloxi",
    state: "Mississippi",
    stateCode: "MS",
    colIndex: 86,
    medianSalary: 37000,
  },
  "missoula-mt": {
    name: "Missoula",
    state: "Montana",
    stateCode: "MT",
    colIndex: 103,
    medianSalary: 45000,
  },
  "great-falls-mt": {
    name: "Great Falls",
    state: "Montana",
    stateCode: "MT",
    colIndex: 89,
    medianSalary: 40000,
  },
  "bozeman-mt": {
    name: "Bozeman",
    state: "Montana",
    stateCode: "MT",
    colIndex: 118,
    medianSalary: 52000,
  },
  "butte-mt": {
    name: "Butte",
    state: "Montana",
    stateCode: "MT",
    colIndex: 86,
    medianSalary: 37000,
  },
  "lincoln-ne": {
    name: "Lincoln",
    state: "Nebraska",
    stateCode: "NE",
    colIndex: 85,
    medianSalary: 47000,
  },
  "bellevue-ne": {
    name: "Bellevue",
    state: "Nebraska",
    stateCode: "NE",
    colIndex: 90,
    medianSalary: 52000,
  },
  "grand-island-ne": {
    name: "Grand Island",
    state: "Nebraska",
    stateCode: "NE",
    colIndex: 82,
    medianSalary: 42000,
  },
  "kearney-ne": {
    name: "Kearney",
    state: "Nebraska",
    stateCode: "NE",
    colIndex: 83,
    medianSalary: 43000,
  },
  "nashua-nh": {
    name: "Nashua",
    state: "New Hampshire",
    stateCode: "NH",
    colIndex: 112,
    medianSalary: 58000,
  },
  "concord-nh": {
    name: "Concord",
    state: "New Hampshire",
    stateCode: "NH",
    colIndex: 105,
    medianSalary: 49000,
  },
  "derry-nh": {
    name: "Derry",
    state: "New Hampshire",
    stateCode: "NH",
    colIndex: 110,
    medianSalary: 56000,
  },
  "dover-nh": {
    name: "Dover",
    state: "New Hampshire",
    stateCode: "NH",
    colIndex: 107,
    medianSalary: 50000,
  },
  "jersey-city-nj": {
    name: "Jersey City",
    state: "New Jersey",
    stateCode: "NJ",
    colIndex: 145,
    medianSalary: 59000,
  },
  "paterson-nj": {
    name: "Paterson",
    state: "New Jersey",
    stateCode: "NJ",
    colIndex: 120,
    medianSalary: 37000,
  },
  "elizabeth-nj": {
    name: "Elizabeth",
    state: "New Jersey",
    stateCode: "NJ",
    colIndex: 128,
    medianSalary: 42000,
  },
  "trenton-nj": {
    name: "Trenton",
    state: "New Jersey",
    stateCode: "NJ",
    colIndex: 112,
    medianSalary: 33000,
  },
  "bismarck-nd": {
    name: "Bismarck",
    state: "North Dakota",
    stateCode: "ND",
    colIndex: 90,
    medianSalary: 49000,
  },
  "grand-forks-nd": {
    name: "Grand Forks",
    state: "North Dakota",
    stateCode: "ND",
    colIndex: 88,
    medianSalary: 43000,
  },
  "minot-nd": {
    name: "Minot",
    state: "North Dakota",
    stateCode: "ND",
    colIndex: 89,
    medianSalary: 45000,
  },
  "west-fargo-nd": {
    name: "West Fargo",
    state: "North Dakota",
    stateCode: "ND",
    colIndex: 94,
    medianSalary: 55000,
  },
  "cranston-ri": {
    name: "Cranston",
    state: "Rhode Island",
    stateCode: "RI",
    colIndex: 118,
    medianSalary: 49000,
  },
  "warwick-ri": {
    name: "Warwick",
    state: "Rhode Island",
    stateCode: "RI",
    colIndex: 116,
    medianSalary: 52000,
  },
  "pawtucket-ri": {
    name: "Pawtucket",
    state: "Rhode Island",
    stateCode: "RI",
    colIndex: 114,
    medianSalary: 37000,
  },
  "east-providence-ri": {
    name: "East Providence",
    state: "Rhode Island",
    stateCode: "RI",
    colIndex: 115,
    medianSalary: 43000,
  },
  "charleston-sc": {
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    colIndex: 113,
    medianSalary: 56000,
  },
  "north-charleston-sc": {
    name: "North Charleston",
    state: "South Carolina",
    stateCode: "SC",
    colIndex: 95,
    medianSalary: 42000,
  },
  "greenville-sc": {
    name: "Greenville",
    state: "South Carolina",
    stateCode: "SC",
    colIndex: 95,
    medianSalary: 52000,
  },
  "spartanburg-sc": {
    name: "Spartanburg",
    state: "South Carolina",
    stateCode: "SC",
    colIndex: 88,
    medianSalary: 42000,
  },
  "rapid-city-sd": {
    name: "Rapid City",
    state: "South Dakota",
    stateCode: "SD",
    colIndex: 92,
    medianSalary: 46000,
  },
  "aberdeen-sd": {
    name: "Aberdeen",
    state: "South Dakota",
    stateCode: "SD",
    colIndex: 86,
    medianSalary: 42000,
  },
  "brookings-sd": {
    name: "Brookings",
    state: "South Dakota",
    stateCode: "SD",
    colIndex: 88,
    medianSalary: 42000,
  },
  "watertown-sd": {
    name: "Watertown",
    state: "South Dakota",
    stateCode: "SD",
    colIndex: 85,
    medianSalary: 42000,
  },
  "south-burlington-vt": {
    name: "South Burlington",
    state: "Vermont",
    stateCode: "VT",
    colIndex: 120,
    medianSalary: 59000,
  },
  "rutland-vt": {
    name: "Rutland",
    state: "Vermont",
    stateCode: "VT",
    colIndex: 100,
    medianSalary: 37000,
  },
  "barre-vt": {
    name: "Barre",
    state: "Vermont",
    stateCode: "VT",
    colIndex: 98,
    medianSalary: 36000,
  },
  "montpelier-vt": {
    name: "Montpelier",
    state: "Vermont",
    stateCode: "VT",
    colIndex: 108,
    medianSalary: 45000,
  },
  "huntington-wv": {
    name: "Huntington",
    state: "West Virginia",
    stateCode: "WV",
    colIndex: 78,
    medianSalary: 33000,
  },
  "parkersburg-wv": {
    name: "Parkersburg",
    state: "West Virginia",
    stateCode: "WV",
    colIndex: 79,
    medianSalary: 35000,
  },
  "morgantown-wv": {
    name: "Morgantown",
    state: "West Virginia",
    stateCode: "WV",
    colIndex: 88,
    medianSalary: 42000,
  },
  "wheeling-wv": {
    name: "Wheeling",
    state: "West Virginia",
    stateCode: "WV",
    colIndex: 77,
    medianSalary: 32000,
  },
  "casper-wy": {
    name: "Casper",
    state: "Wyoming",
    stateCode: "WY",
    colIndex: 89,
    medianSalary: 47000,
  },
  "laramie-wy": {
    name: "Laramie",
    state: "Wyoming",
    stateCode: "WY",
    colIndex: 90,
    medianSalary: 42000,
  },
  "gillette-wy": {
    name: "Gillette",
    state: "Wyoming",
    stateCode: "WY",
    colIndex: 88,
    medianSalary: 52000,
  },
  "rock-springs-wy": {
    name: "Rock Springs",
    state: "Wyoming",
    stateCode: "WY",
    colIndex: 87,
    medianSalary: 49000,
  },
  "aurora-co": {
    name: "Aurora",
    state: "Colorado",
    stateCode: "CO",
    colIndex: 103,
    medianSalary: 50000,
  },
  "fort-collins-co": {
    name: "Fort Collins",
    state: "Colorado",
    stateCode: "CO",
    colIndex: 108,
    medianSalary: 56000,
  },
  "aurora-il": {
    name: "Aurora",
    state: "Illinois",
    stateCode: "IL",
    colIndex: 96,
    medianSalary: 49000,
  },
  "naperville-il": {
    name: "Naperville",
    state: "Illinois",
    stateCode: "IL",
    colIndex: 114,
    medianSalary: 76000,
  },
  "rockford-il": {
    name: "Rockford",
    state: "Illinois",
    stateCode: "IL",
    colIndex: 82,
    medianSalary: 35000,
  },
  "st-louis-mo": {
    name: "St. Louis",
    state: "Missouri",
    stateCode: "MO",
    colIndex: 87,
    medianSalary: 37000,
    localIncomeTax: 0.01,
    localTaxName: "St. Louis earnings tax",
  },
  "springfield-mo": {
    name: "Springfield",
    state: "Missouri",
    stateCode: "MO",
    colIndex: 82,
    medianSalary: 36000,
  },
  "columbia-mo": {
    name: "Columbia",
    state: "Missouri",
    stateCode: "MO",
    colIndex: 88,
    medianSalary: 42000,
  },
  "henderson-nv": {
    name: "Henderson",
    state: "Nevada",
    stateCode: "NV",
    colIndex: 108,
    medianSalary: 52000,
  },
  "reno-nv": {
    name: "Reno",
    state: "Nevada",
    stateCode: "NV",
    colIndex: 110,
    medianSalary: 49000,
  },
  "north-las-vegas-nv": {
    name: "North Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    colIndex: 102,
    medianSalary: 43000,
  },
  "buffalo-ny": {
    name: "Buffalo",
    state: "New York",
    stateCode: "NY",
    colIndex: 89,
    medianSalary: 35000,
  },
  "rochester-ny": {
    name: "Rochester",
    state: "New York",
    stateCode: "NY",
    colIndex: 88,
    medianSalary: 33000,
  },
  "yonkers-ny": {
    name: "Yonkers",
    state: "New York",
    stateCode: "NY",
    colIndex: 148,
    medianSalary: 45000,
  },
  "cincinnati-oh": {
    name: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    colIndex: 88,
    medianSalary: 42000,
    localIncomeTax: 0.018,
    localTaxName: "Cincinnati municipal income tax",
  },
  "cleveland-oh": {
    name: "Cleveland",
    state: "Ohio",
    stateCode: "OH",
    colIndex: 83,
    medianSalary: 27000,
    localIncomeTax: 0.025,
    localTaxName: "Cleveland municipal income tax",
  },
  "dayton-oh": {
    name: "Dayton",
    state: "Ohio",
    stateCode: "OH",
    colIndex: 82,
    medianSalary: 32000,
  },
  "pittsburgh-pa": {
    name: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    colIndex: 94,
    medianSalary: 37000,
    localIncomeTax: 0.03,
    localTaxName: "Pittsburgh city income tax",
  },
  "allentown-pa": {
    name: "Allentown",
    state: "Pennsylvania",
    stateCode: "PA",
    colIndex: 96,
    medianSalary: 35000,
  },
  "erie-pa": {
    name: "Erie",
    state: "Pennsylvania",
    stateCode: "PA",
    colIndex: 82,
    medianSalary: 32000,
  },
  "knoxville-tn": {
    name: "Knoxville",
    state: "Tennessee",
    stateCode: "TN",
    colIndex: 89,
    medianSalary: 42000,
  },
  "chattanooga-tn": {
    name: "Chattanooga",
    state: "Tennessee",
    stateCode: "TN",
    colIndex: 90,
    medianSalary: 43000,
  },
  "provo-ut": {
    name: "Provo",
    state: "Utah",
    stateCode: "UT",
    colIndex: 103,
    medianSalary: 52000,
  },
  "west-valley-city-ut": {
    name: "West Valley City",
    state: "Utah",
    stateCode: "UT",
    colIndex: 100,
    medianSalary: 47000,
  },
  "west-jordan-ut": {
    name: "West Jordan",
    state: "Utah",
    stateCode: "UT",
    colIndex: 101,
    medianSalary: 52000,
  },
  "virginia-beach-va": {
    name: "Virginia Beach",
    state: "Virginia",
    stateCode: "VA",
    colIndex: 103,
    medianSalary: 56000,
  },
  "norfolk-va": {
    name: "Norfolk",
    state: "Virginia",
    stateCode: "VA",
    colIndex: 99,
    medianSalary: 42000,
  },
  "chesapeake-va": {
    name: "Chesapeake",
    state: "Virginia",
    stateCode: "VA",
    colIndex: 101,
    medianSalary: 58000,
  },
  "spokane-wa": {
    name: "Spokane",
    state: "Washington",
    stateCode: "WA",
    colIndex: 92,
    medianSalary: 40000,
  },
  "tacoma-wa": {
    name: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    colIndex: 108,
    medianSalary: 49000,
  },
  "bellevue-wa": {
    name: "Bellevue",
    state: "Washington",
    stateCode: "WA",
    colIndex: 165,
    medianSalary: 101000,
  },
  "madison-wi": {
    name: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    colIndex: 100,
    medianSalary: 52000,
  },
  "green-bay-wi": {
    name: "Green Bay",
    state: "Wisconsin",
    stateCode: "WI",
    colIndex: 90,
    medianSalary: 42000,
  },
  "kenosha-wi": {
    name: "Kenosha",
    state: "Wisconsin",
    stateCode: "WI",
    colIndex: 92,
    medianSalary: 43000,
  },
  "san-jose-ca": {
    name: "San Jose",
    state: "California",
    stateCode: "CA",
    colIndex: 188,
    medianSalary: 97000,
  },
  "fresno-ca": {
    name: "Fresno",
    state: "California",
    stateCode: "CA",
    colIndex: 98,
    medianSalary: 40000,
  },
  "long-beach-ca": {
    name: "Long Beach",
    state: "California",
    stateCode: "CA",
    colIndex: 145,
    medianSalary: 52000,
  },
  "tucson-extra-az": {
    name: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    colIndex: 102,
    medianSalary: 47000,
  },
  "chandler-az": {
    name: "Chandler",
    state: "Arizona",
    stateCode: "AZ",
    colIndex: 105,
    medianSalary: 59000,
  },
  "scottsdale-az": {
    name: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    colIndex: 125,
    medianSalary: 73000,
  },
  "savannah-ga": {
    name: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    colIndex: 96,
    medianSalary: 42000,
  },
  "columbus-ga": {
    name: "Columbus",
    state: "Georgia",
    stateCode: "GA",
    colIndex: 85,
    medianSalary: 37000,
  },
  "augusta-ga": {
    name: "Augusta",
    state: "Georgia",
    stateCode: "GA",
    colIndex: 84,
    medianSalary: 36000,
  },
  "fort-lauderdale-fl": {
    name: "Fort Lauderdale",
    state: "Florida",
    stateCode: "FL",
    colIndex: 118,
    medianSalary: 49000,
  },
  "st-petersburg-fl": {
    name: "St. Petersburg",
    state: "Florida",
    stateCode: "FL",
    colIndex: 100,
    medianSalary: 45000,
  },
  "hialeah-fl": {
    name: "Hialeah",
    state: "Florida",
    stateCode: "FL",
    colIndex: 112,
    medianSalary: 37000,
  },
  "greensboro-nc": {
    name: "Greensboro",
    state: "North Carolina",
    stateCode: "NC",
    colIndex: 88,
    medianSalary: 40000,
  },
  "durham-nc": {
    name: "Durham",
    state: "North Carolina",
    stateCode: "NC",
    colIndex: 100,
    medianSalary: 49000,
  },
  "winston-salem-nc": {
    name: "Winston-Salem",
    state: "North Carolina",
    stateCode: "NC",
    colIndex: 87,
    medianSalary: 39000,
  },
};

export const CITY_SLUGS = Object.keys(CITY_DATA);
